services:
  - type: web
    name: bisca-lobby
    runtime: docker
    plan: free
    region: frankfurt
    dockerfilePath: ./Dockerfile.lobby
    dockerContext: .
    healthCheckPath: /health
    autoDeployTrigger: commit
    envVars:
      - key: NODE_ENV
        value: production
